# _config.yml

# Specify the directory where your SCSS files are located
sass:
  sass_dir: _sass            # Directory for SCSS files (relative to the root of the docs folder)
  style: compressed           # Output style for compiled CSS (compressed)

# Exclude compiled CSS from Jekyll processing
exclude:
  - assets/css/main.css       # Adjust the path based on the root directory of the site
